### ISSUE TITLE
日付別勤怠一覧ページ

### ISSUE THREAD

**Issue by kubo-haruka** [kubo-haruka/Atte#16]
- [x] view作成
 - [x] コントローラー作成
 
ページネーションはやらない
日付選択はやらない
12/28 23時まで

**Comment by kubo-haruka** [comment]
@gem-yours 

質問です。
初歩的な質問で申し訳御座いませんが、
同じユーザーで異なるデータを所有している時にそれぞれのデータごとに改行されるにはどうしたら良いでしょうか。。
ご教授いただけましたら幸いです。
宜しくお願い致します。

**Comment by kubo-haruka** [comment]
@gem-yours 

また、Carbonでも使用方法に躓いています。
教材を確認しながら、セットアップまでは完了したのですが、
特定の休憩時間／勤務時間の減算をどのように行うのかが理解できておりません。。
こちらも合わせてアドバイス頂けましたら幸いです。
宜しくお願い致します。
https://lms.coachtech.site/learning-chapters/be259018-2a2c-4869-8db0-4d4c67dd259

**Comment by gem-yours** [comment]
日付の処理に関してはCarbonを利用してあげると良いです。
下記のリンクが参考になると思います。
https://qiita.com/yudsuzuk/items/ff894bd0b76d4657741d#日付の差分

ちなみにリンクをうまく開くことができなかったのですが、どのような内容だったでしょうか？

**Comment by kubo-haruka** [comment]
@gem-yours 
有り難う御座います。
教材に記載されている内容も似たような内容でした。
頂いたサイトも確認したのですが、添付箇所はどのように指示するのでしょうか。。そこがいまいち理解できずに躓いてしまっています。
お手数をお掛け致しますが、ご確認をお願い致します。
<img width="521" alt="スクリーンショット 2023-01-12 20 26 21" src="https://user-images.githubusercontent.com/112786056/212055288-08538f59-46fb-43fb-8faa-cc9cfe8d9b78.png">

また、下記についてもアドバイス頂けましたら幸いです。
宜しくお願い致します。
https://github.com/kubo-haruka/Atte/issues/16#issuecomment-1379887773

**Comment by gem-yours** [comment]
> 同じユーザーで異なるデータを所有している時にそれぞれのデータごとに改行されるにはどうしたら良いでしょうか。。

申し訳ございません、見落としていました。

こちらの問題は表示を変えるよりもデータのアクセスの方法を変える方が適切です。具体的には`$users`と`$rests`をviewにわたすのをやめて`$attendances`のみを渡すようにします。
Attendanceからユーザを取得するメソッドを用意してあるので、viewに`User::all()`の結果を渡さなくてもユーザ情報を表示することができます。
https://github.com/kubo-haruka/Atte/blob/4a8b317d92b44cc2405a3b3806710cef885c189a/app/Models/Attendace.php#L24

上記でuserメソッドを用意してあるので`{{ attendance->user->name }}`のようにアクセスが可能です。`Rest`に関しても同じようにAttendance経由でアクセスするようにお願いいたします。

**Comment by gem-yours** [comment]
> 添付箇所はどのように指示するのでしょうか

`new Carbon($attendance->start_time)`のように、time型のデータをCarbonに渡してあげると良いです。

**Comment by kubo-haruka** [comment]
@gem-yours 

2件、面談時に確認させていただけると助かります。
宜しくお願い致します。

> 上記でuserメソッドを用意してあるので`{{ attendance->user->name }}`のようにアクセスが可能です。`Rest`に関しても同じようにAttendance経由でアクセスするようにお願いいたします。

> `new Carbon($attendance->start_time)`のように、time型のデータをCarbonに渡してあげると良いです。

**Comment by kubo-haruka** [comment]
- [x] Attendanceマイグレーション修正
- [x] シーダーで情報入力
- [ ] Attendance：カーボン入力
- [ ] Rests：カーボン入力
1/16　24時まで

**Comment by kubo-haruka** [comment]
@gem-yours 
Carbonの作成まで進行しているのですが、
下記エラーが表示されてしまい、解決できずにいます。。
`Call to a member function rest_time() on null (View: /Applications/MAMP/htdocs/Atte/resources/views/attendace.blade.php)`

echo~returnまでの記述もまだこれだと思えていないのですが。。
nullは新たに作成したシーダーのデータで休憩時間を入れ込んでいないデータを作成したのですが、そちらが原因でしょうか。
その場合は、テーブルのnullの規制を解除（マイグレーションの修正）が必要でしょうか。

お手数をお掛け致しますが、アドバイス頂けましたら幸いです。
宜しくお願い致します。

**Comment by gem-yours** [comment]
`Call to a member function rest_time() on null (View: /Applications/MAMP/htdocs/Atte/resources/views/attendace.blade.php)`
このエラーは`rest`がnullであることを意味しています。ですので、

> nullは新たに作成したシーダーのデータで休憩時間を入れ込んでいないデータを作成したのですが、そちらが原因でしょうか。

これが正解ですね。
対応としては、restがnullのとき(まだ休憩していない勤怠) は休憩時間を計算する代わりに空白にしてあげるという風にやるのが良いです。

**Comment by kubo-haruka** [comment]
@gem-yours 

ようやくエラーの表示がされないようにまで行き着きましたが。。
２点どうしても解決できませんでした。

`        @if($attendances->isEmpty())
        <td>{{ $attendance->rests->rest_time() }}</td>
        @endif`

isEmptyで入れ込んでみたところ、エラー表示はされなくなりましたが、休憩時間が表示されない状態です。。
他のissetやis_nullだと「nullの時＋0の時」などに当てはまらないのかと思いましたが、認識が異なりますでしょうか。

また、勤務の合計時間の数値がおかしいのですが、こちらはどのような方法で表示させるのが正しいでしょうか。

お手数をお掛け致しますが、改めてアドバイス頂けますでしょうか。
宜しくお願い致します。

**Comment by gem-yours** [comment]
> $attendances->isEmpty()

$attendance**s** は`Attendance::all()`の実行結果です。勤怠に関連する休憩の有無には関係ないので、if文の中身は常に実行されなくなってしまいます。

> 他のissetやis_nullだと「nullの時＋0の時」などに当てはまらないのかと思いましたが、

`$attendance->rest`がnullのときに`$attendance->rest->rest_time()`を実行しようとするとエラーになってしまいます。そのため、「nullの時＋0の時」は休憩時間を表示しないのであれば、`$attendance->rest`がnullかどうか判定するifと`$attendance->rests->rest_time()`が0かどうか判定するifの２つが必要になります。

単純なタイプミスだとは思いますが、`$attendance->rests->rest_time()`は`$attendance->rest->rest_time()` (restとrest**s**)ですね。

**Comment by gem-yours** [comment]
`7:40:00`が`7:460:27600`のように表示されていると思います。

460[分] - 7[時間] * 60[分] = 40[分]
27600[秒] - 460[分] * 3600[秒] = 0[秒]

のように、大きな単位の時間を引いてあげる必要があります。

**Comment by kubo-haruka** [comment]
@gem-yours 
アドバイスいただき有り難う御座いました。

なんとか自力で面談日までに解決したかったのですが、
if（null）のエラー分のみわかりませんでした。。

また、時間の表示は「00」のときは「0」になってしまうのですが、こちらは仕方がないのでしょうか。何か他に解決方法がありましたらご教授頂きたいです。
宜しくお願い致します。
