### ISSUE TITLE
ログイン／ログアウト

### ISSUE THREAD

**Issue by kubo-haruka** [kubo-haruka/Atte#3]
#2 を先にやる
- [x] ユーザーの作成
12/6 21時完了予定

**Comment by kubo-haruka** [comment]
@gem-yours 
Seederでファイルの作成まで行いましたが、
Modelが設計書等の確認後になるかと思い、一度後に回したいと思いますが、よろしいでしょうか。

**Comment by gem-yours** [comment]
@kubo-haruka 
大丈夫です！

**Comment by kubo-haruka** [comment]
#6 が完了次第やる

**Comment by kubo-haruka** [comment]
12/22 23時まで
- [x] register：view作成
- [x] login：view作成
- [x] user：シーディング作成

**Comment by kubo-haruka** [comment]
@gem-yours 
registerのViewを作成致しました。
一旦、Viewのみで、挙動等については置いてます。
宜しくお願い致します。

コミット時にissue番号を入れ漏れてました。。
→register view作成
https://github.com/kubo-haruka/Atte/tree/login

**Comment by gem-yours** [comment]
viewに関してはこれでOKです！

**Comment by kubo-haruka** [comment]
@gem-yours 
ご確認有り難うございました！

**Comment by kubo-haruka** [comment]
@gem-yours 
上記viewの作成が完了致しました。
register同様、挙動は一旦置いてます。
宜しくお願い致します。

**Comment by gem-yours** [comment]
ログインviewも大丈夫です。

**Comment by kubo-haruka** [comment]
@gem-yours 
ご確認有り難う御座いました！

**Comment by kubo-haruka** [comment]
@gem-yours 
シーディングの作成が完了致しました。

今回テーブルに`update_at`を入れなかったので、エラーが出たため、
モデルに`public $timestamps = false;`を入れました。
上記コードはずっと入れておいたままでも良いのでしょうか。
シーディングの内容も含めて、ご確認をお願い致します。

また、viewの作成までできましたが、
情報を入力したらデータベースに保存されるようになるなど、
挙動も含めて、完了まで進行した方が良いでしょうか。
→他のissueが先の方が良いなどあればアドバイス頂きたいです！

宜しくお願い致します。

**Comment by gem-yours** [comment]
> 今回テーブルにupdate_atを入れなかったので、エラーが出たため、
モデルにpublic $timestamps = false;を入れました。
上記コードはずっと入れておいたままでも良いのでしょうか。

上記のコードがないとエラーになってしまうので、入れておく必要があります。

> 情報を入力したらデータベースに保存されるようになるなど、
挙動も含めて、完了まで進行した方が良いでしょうか。

データベースの保存などの挙動も含めて完了でお願い致します。現状の時点で、ログインボタンや登録ボタンを押すとbreezeのログイン・登録処理が呼び出されるはずです。一度動かして動作確認をしてみてください。(リダイレクト先が`/dashbord`になっているので、404は出ると思いますがDBにユーザー情報は登録されているはずです。)

**Comment by gem-yours** [comment]
https://github.com/kubo-haruka/Atte/blob/3a24f1b3dbabdfda23d6527b2e056b4e32bdafcf/database/seeders/UserTableSeeder.php#L20

パスワードは平文 (人間が読んでわかる形式) で保存されるのではなく、暗号化して保存されます。(暗号化することで万が一DBの中身を盗み取られたとしても不正なログインを防ぐことができます。) DBには暗号化されたパスワードが保存されているので、単純に 'password' => 'testest'  のようにしてしまうと暗号化した結果が”testtest”になるようなパスワードと解釈されてしまいます。
bcrypt関数を利用して、`bcrypt('testtest')`のように記述することで、暗号化して保存できます。

**Comment by kubo-haruka** [comment]
@gem-yours 
ご確認有り難う御座いました！

会員登録画面のRouteServiceProviderの20行目をログイン後の画面の「/home」としたのですが、画面が特に切り替わることなく、/registerのままでDBにも保存されていませんでした。。
お手数をおかけいたしますが、どこが不足しているかご教授いただけますでしょうか。

また、パスワードはUserTableSeeder.phpで`'password' => bcrypt('testtest')`のように記載をしたら良いと言うことでしょうか。
調べてみても理解が追いつきませんでした。。

**Comment by gem-yours** [comment]
> 会員登録画面のRouteServiceProviderの20行目をログイン後の画面の「/home」としたのですが、画面が特に切り替わることなく、/registerのままでDBにも保存されていませんでした。

シーディングファイルと同じメールアドレスで登録を行っています？おそらくメールアドレス重複のバリデーションエラーが発生しているものと思われます。もしそれ以外の原因だった場合は、bladeファイルに`{{ $errors ?? ''}}`の記述を試しに追加してみて何かエラーが発生していないか確認してみて下さい。

https://github.com/kubo-haruka/Atte/blob/3a24f1b3dbabdfda23d6527b2e056b4e32bdafcf/database/seeders/UserTableSeeder.php#L19

合わせてですが、こちらのメールアドレスは実際に使用されているものです？テストデータに実際のメールアドレスを使うのはあまり望ましくないです。実は[テスト用のアドレス](https://ja.wikipedia.org/wiki/Example.com)が用意されているのでそちらを使ってあげましょう。

**Comment by gem-yours** [comment]
> パスワードはUserTableSeeder.phpで'password' => bcrypt('testtest')のように記載をしたら良いと言うことでしょうか。

結論としてはその解釈で大丈夫です。
ユーザ作成をした後にDBを覗いてみると下のようになっています。

```
+----+------+------------------+--------------------------------------------------------------+
| id | name | email            | password                                                     |
+----+------+------------------+--------------------------------------------------------------+
|  1 | foo  | a123@example.com | $2y$10$VP0THfUpIOT2QePPZA8yUet4xKrkO6OLLJSGDokD4o.D1lGNsFKzS |
+----+------+------------------+--------------------------------------------------------------+
```

パスワード欄には「password」という文字列を打ち込んだのですが、上記のようにまったく違う文字列になっています。この文字列が暗号化されたパスワードです。
「password」という文字列でログインするためには、上記のレコードを作成する必要があるので、単純に実装するとシーディングファイルを以下のようにする必要があります。
```
$user = [
            'name' => 'foo',
            'email' => 'a123@example.com ',
            'password' => '$2y$10$VP0THfUpIOT2QePPZA8yUet4xKrkO6OLLJSGDokD4o.D1lGNsFKzS'
        ];
User::create($user);
```
ですが、この方法ではログイン時に入力するパスワードがシーディングファイルを見ただけではわからなくなってしまい、新たに開発に参入する人がログインできなくなってしまいます。そこで、「password」という文字列を「$2y$10$VP0THfUpIOT2QePPZA8yUet4xKrkO6OLLJSGDokD4o.D1lGNsFKzS」という文字列に暗号化してくれる`bcrypt`という関数を使用する必要が出てきます。`bcrypt(password)'`を実行すると「$2y$10$VP0THfUpIOT2QePPZA8yUet4xKrkO6OLLJSGDokD4o.D1lGNsFKzS」という文字列になるので、以下のような置き換えが可能になります。
```
$user = [
            'name' => 'foo',
            'email' => 'a123@example.com ',
            'password' => bycrypt('password')
        ];
User::create($user);
```
