### ISSUE TITLE
ER図の作成／テーブル仕様書作成

### ISSUE THREAD

**Issue by kubo-haruka** [kubo-haruka/Atte#4]
12/6 22時完了予定

**Comment by kubo-haruka** [comment]
@gem-yours 
ご確認をお願い致します。

テーブル設計
<img width="524" alt="テーブル設計" src="https://user-images.githubusercontent.com/112786056/205645097-cec30234-51bc-4644-8cde-bf882e33f9b2.png">

ER図
![index](https://user-images.githubusercontent.com/112786056/205645113-b2a77153-407a-444b-915e-938ac7f583b1.png)

**Comment by gem-yours** [comment]
@kubo-haruka 
# テーブル定義について
## usersテーブル
- passwordはunique制約はなくても大丈夫です (違うユーザが同じパスワードを使っても問題は起きません)
- created_at/updated_atは必要でしょうか？これらのカラムは`timestamps`を利用することで自動で入れることはできますが、毎回入れる必要はないです。
- idはユーザを区別するためのものなので`unique key`が必要です。
## attendancesテーブル
- id・timestampに関してはuserと同様です

# ER図
- 休憩開始・終了のデータを記録する必要があります。

**Comment by kubo-haruka** [comment]
@gem-yours 

ご確認有り難う御座いました！
追加／修正致しましたので、ご確認をお願い致します。

### usersテーブル
> created_at/updated_atは必要でしょうか？これらのカラムはtimestampsを利用することで自動で入れることはできますが、毎回入れる必要はないです。
こちらはテストの際、毎回修正をいただいていた箇所なので、今回も両方のテーブルに加えておりました。。
<img width="519" alt="テーブル設計_修正" src="https://user-images.githubusercontent.com/112786056/205944602-cfa9f9c4-6a16-42ad-b56a-ae45cfadc856.png">
![index](https://user-images.githubusercontent.com/112786056/205944840-93d0cd47-e690-478c-bc10-3bac4461c070.png)

**Comment by kubo-haruka** [comment]
![index](https://user-images.githubusercontent.com/112786056/205944840-93d0cd47-e690-478c-bc10-3bac4461c070.png)

**Comment by gem-yours** [comment]
@kubo-haruka 

ご修正ありがとうございます。

- usersテーブルは大丈夫ですが、他のテーブルのidがuniqueではなくなってしまっていますね。
- 若干好みの問題もあるのですが、`rest_start`は単に`start`のほうが収まりが良くなります。attendancesテーブルと合わせるなら`start_time`みたいな感じですね。
``` php
$rest = Rest::find(1);
$rest.rest_start // restが2つ出てきて冗長
$rest.start // startだけで休憩開始時間と読める
```
- 勤怠の開始時間がTIME型となっていますが、TIME型は`hh:mm:ss`のようなフォーマットになっており、日付の情報がありません。created_atを使うことも可能ではありますが設計的にはあまり良くないです。詳しくは下の項目をご確認していただければ幸いです。


> 毎回修正をいただいていた箇所なので

この点については一概にどちらが良い言い切ることが難しいのですが、考える参考になる資料をいくつか添付しておきます。
[肯定的な意見](https://songmu.jp/riji/entry/2019-10-21-created_at-update_at.html)
[否定的な意見](https://softwareengineering.stackexchange.com/questions/415517/benefits-of-created-at-or-updated-at-columns-in-database-design)
個人的にはデータを追跡しやすくするのはログの仕事で、DBに担保させるべきではないと考えています。
ですが、保険として入れておきたいという意見も納得が行くものなので、考え方によりけりでどちらが良いとは比較することは難しいです。
ただ、アプリケーションロジックとして使う (例：created_adを勤怠の開始日として扱う) のは一般的に良くないとされているので、`updated_at`などを入れて役に立つのは運用のフェーズになってからです。今回の演習の中で役に立つことはないので、今は無理に入れる必要はないのではないかと言うのが私見です。(もちろん、上記を踏まえた上であったほうが良いと判断されたなら入れていただいてもOKです。)

**Comment by kubo-haruka** [comment]
@gem-yours 
ご確認有り難う御座いました。

> 若干好みの問題もあるのですが、rest_startは単にstartのほうが収まりが良くなります。attendancesテーブルと合わせるならstart_timeみたいな感じですね。
こちら理解致しました。勉強になります！

> 勤怠の開始時間がTIME型となっていますが、TIME型はhh:mm:ssのようなフォーマットになっており、日付の情報がありません。created_atを使うことも可能ではありますが設計的にはあまり良くないです。詳しくは下の項目をご確認していただければ幸いです。
頂いた情報を確認いたしました。
運用のフェーズになれば必要だが、現時点では良いとされないという点で、`updated_at` `updated_at`はなしで行こうと思います。

お手数をおかけいたしますが、再度ご確認をお願い致します。
<img width="523" alt="テーブル仕様書_修正1207" src="https://user-images.githubusercontent.com/112786056/206182004-576fda27-bd57-4eaf-8b70-d464388475c5.png">
![index](https://user-images.githubusercontent.com/112786056/206181997-a0219cf5-8ed7-48a1-b382-a9431878774d.png)

**Comment by gem-yours** [comment]
@kubo-haruka 
ER図・テーブル定義確認いたしました。この形で大丈夫です！

作業が完了いたしましたので、こちらのissueはcloseお願いいたします。

**Comment by kubo-haruka** [comment]
@gem-yours 
有り難う御座います！
closeの件、承知致しました。
READMEも完了させたいと思います！
