### ISSUE TITLE
基本設計書作成

### ISSUE THREAD

**Issue by kubo-haruka** [kubo-haruka/Atte#6]
- [x] Route,Controller：12/7 1h
- [x] Model：12/7 30m
- [x] View：12/7 30m
- [x] バリデーション：12/7 1h

**Comment by kubo-haruka** [comment]
@gem-yours 
何度もすみません。
下記基本設計書はご確認頂かずに進行となるのでしょうか。
WBSシート上では「テーブル仕様書／ER図」で作成／修正と記載があるのですが、基本設計書はなかったので念の為の確認です。。
https://docs.google.com/spreadsheets/d/14-MVvQQOaQ8bRccrj7jNdn5d2rqeT0OaH_oL70oVFQY/edit#gid=1265544478

お手数をお掛け致しますが、宜しくお願い致します。

**Comment by gem-yours** [comment]
@kubo-haruka 
WBSに記載が入っていないですが、確認いたします。
基本的にWBSはあまり更新せず、進捗管理やご質問についてはgithub上で進行する予定です。ですので、WBSの情報は見ていただかなくてもOKです。
現状の基本設計書をもとにレビューを進めても大丈夫でしょうか？

**Comment by kubo-haruka** [comment]
@gem-yours 
有り難う御座います。

> 基本的にWBSはあまり更新せず、進捗管理やご質問についてはgithub上で進行する予定です。ですので、WBSの情報は見ていただかなくてもOKです。
承知致しました！

> 現状の基本設計書をもとにレビューを進めても大丈夫でしょうか？
ご確認をお願い致します。

**Comment by gem-yours** [comment]
@kubo-haruka 
# Routes/Controller
ページ一覧にurlと対応するページがありますが、そのurlしか使ってはいけないという意味ではないです。必要に応じて新しいurlを定義して使用してください。

- [x] ログイン画面を表示するアクションがないです。
- [x] `/login`というurlにリクエストした結果ログアウトが発生するというのは直感的でないです。
- [x] 勤務や開始・終了はそれぞれ一つのアクションにしてください。
- [x] 認証必須かどうかについても埋めておいてください。

**Comment by kubo-haruka** [comment]
@gem-yours 

> ページ一覧にurlと対応するページがありますが、そのurlしか使ってはいけないという意味ではないです。必要に応じて新しいurlを定義して使用してください。

そうなんですね！必ずイコールでないといけないと思っていました。

修正致しました。
ご確認をお願い致します！
https://docs.google.com/spreadsheets/d/14-MVvQQOaQ8bRccrj7jNdn5d2rqeT0OaH_oL70oVFQY/edit#gid=1265544478

**Comment by gem-yours** [comment]
アクション名はメソッド名と等しいので、`.` (ドット) は使えないです。複数の単語からなるメソッド名を使いたいときにはキャメルケースを使うのがphpでは一般的です。例えば、`attendance.start`はキャメルケースにすると`attendanceStart`になります。
また、メソッド名はできるだけ英文法に合わせてあげた方が良いです。`attendanceStart`→`startAttendance`のような形ですね。
他の場所についてはOKです。上記の修正が終わればcloseしてください。

**Comment by kubo-haruka** [comment]
@gem-yours 
有り難う御座います。
そのように記載すればよかったんですね！
修正致しましたので、closeします！
