### ISSUE TITLE
 Model作成

### ISSUE THREAD

**Issue by kubo-haruka** [kubo-haruka/Atte#8]
- [x] Usersテーブル操作用モデル→デフォルトで入っているmodelを使用
- [x] Attendacesテーブル操作用モデル
- [x] Restsテーブル作成用モデル

12/9 23時までに完了

**Comment by kubo-haruka** [comment]
コーディング：12/8 24時までに完了
- [x] Userモデル
- [x] Attendaceモデル
- [x] Restモデル

**Comment by kubo-haruka** [comment]
@gem-yours 
modelの作成が完了しました。
ご確認をお願い致します。
※明日は #9 を行う予定で作成してみました。

## 質問です
合わせてで申し訳御座いません。
先に確認しておけばよかったのですが。。
branchはissueごとに作成した方が良いのでしょうか？

issue：モデル作成
→「branch：Model」を作成して「branch：Model」にコミット
→もしかしたら、このように合わせた方が良かったのかも。。と思い、確認でした。

宜しくお願い致します。

**Comment by gem-yours** [comment]
> branchはissueごとに作成した方が良いのでしょうか？

理想的には一つのissueにつき一つのbranchです。

また、作業が完了してレビューの段階に入る場合はpull requestの作成をしていただけると助かります。（[マニュアル](https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request#creating-the-pull-request)）

**Comment by gem-yours** [comment]
今回はこちらで作成いたしました。上記のpull requestをご覧ください。

**Comment by kubo-haruka** [comment]
@gem-yours 
承知致しました！
やってみます！
