### ISSUE TITLE
テーブル作成

### ISSUE THREAD

**Issue by kubo-haruka** [kubo-haruka/Atte#9]
マイグレーションでテーブル作成：12/9 19時まで
- [x] usersテーブル
- [x] attendacesテーブル
- [x] restsテーブル

メゾット内容作成：12/9 24時まで
- [x] usersテーブル
- [x] attendacesテーブル
- [x] restsテーブル

**Comment by kubo-haruka** [comment]
テーブル作成 #11

**Comment by kubo-haruka** [comment]
@gem-yours 
READMEのコンフリクト、
テーブル作成のpull requestsまで完了しました。
ご確認をお願い致します。

**Comment by kubo-haruka** [comment]
ログイン／ログアウト　#3 
READMEのコンフリクトを解決したら、上記のissueが完了になってしまいました。。
こちらはまだタスクがあったのですが、再度開いても良いのでしょうか？

**Comment by gem-yours** [comment]
すみません、メッセージの確認が遅れてしまいました。
issueを再度開いていただくのは大丈夫です！
